### ISSUE TITLE
SameSite cookie

### ISSUE THREAD

**Issue by klapuch** [klapuch/Remembrall#37]
Implement SameSite cookie with strict mode

**Comment by Calico90** [comment]
For inspiration see: https://github.com/Calico90/CodeIgniterSecureCookies/blob/master/application/hooks/secureCookies.php

I did quite some research regarding the implementation of SameSite since it's not yet supported by PHP. In order to achieve this there is one important thing to consider. A different Set-Cookie header can be send multiple times. You might want to use some kind of output buffering in order to list the headers with `headers_list()` and to override them at the proper moment with the new version.  Ping me if you have some questions.
